### ISSUE TITLE
Update the description 

### ISSUE THREAD

**Issue by this-oliver** [LFredin/LibrarySystem2#2]
Hi, 
Please update the description in a more formal format. Thanks. Regards. Sincerely. Yours truly.
Oliver "Oliver Manzi" Manzi

**Comment by fredin-94** [comment]
Dear sir/madam, we sincerely do apologize for the inconvenicene and we regret to inform thee that the Library System(TM) has been out of production since early 2018(?) and is no longer in use, thus we cannot assist you in any matters regarding the system.

Yours truly, 
disgruntled Library System(TM) employee.
